import { CandidateDetail, Note } from '../../../types/candidate';

export let mockCandidates: CandidateDetail[] = [
  {
    id: 'cand-001',
    name: 'Laura Mendoza',
    full_name: 'Laura Mendoza',
    email: 'laura.mendoza@example.com',
    phone: '+34 612 345 678',
    position: 'Senior Frontend Engineer',
    role: 'Senior Frontend Engineer',
    status: 'active',
    stage: 'interview',
    linkedin: 'https://linkedin.com/in/lauramendoza',
    cv: 'https://example.com/cv/laura-mendoza.pdf',
    years_of_experience: 6,
    applied_at: '2026-08-15T10:00:00Z',
    notes: [
      {
        id: 'note-101',
        content: 'Excelente perfil técnico. Muy buena comunicación en la primera llamada.',
        createdAt: '2026-08-16T11:30:00Z',
      },
    ],
  },
  {
    id: 'cand-002',
    name: 'Carlos Ruiz',
    full_name: 'Carlos Ruiz',
    email: 'carlos.ruiz@example.com',
    phone: '+34 699 888 777',
    position: 'Full Stack Developer',
    role: 'Full Stack Developer',
    status: 'active',
    stage: 'technical_test',
    linkedin: 'https://linkedin.com/in/carlosruiz',
    cv: 'https://example.com/cv/carlos-ruiz.pdf',
    years_of_experience: 4,
    applied_at: '2026-08-18T14:20:00Z',
    notes: [
      {
        id: 'note-102',
        content: 'Enviada prueba técnica. Fecha límite de entrega: viernes.',
        createdAt: '2026-08-19T09:00:00Z',
      },
    ],
  },
  {
    id: 'cand-003',
    name: 'Sofía Benítez',
    full_name: 'Sofía Benítez',
    email: 'sofia.benitez@example.com',
    phone: '+1 305 555 0199',
    position: 'Product Designer (UI/UX)',
    role: 'Product Designer (UI/UX)',
    status: 'hired',
    stage: 'hired',
    linkedin: 'https://linkedin.com/in/sofiabenitez',
    cv: 'https://example.com/cv/sofia-benitez.pdf',
    years_of_experience: 5,
    applied_at: '2026-07-10T08:00:00Z',
    notes: [
      {
        id: 'note-103',
        content: 'Oferta aceptada. Incorporación prevista para el 1 de octubre.',
        createdAt: '2026-07-25T16:00:00Z',
      },
    ],
  },
  {
    id: 'cand-004',
    name: 'Alejandro Gómez',
    full_name: 'Alejandro Gómez',
    email: 'alejandro.gomez@example.com',
    phone: '+34 611 222 333',
    position: 'DevOps & Cloud Engineer',
    role: 'DevOps & Cloud Engineer',
    status: 'on_hold',
    stage: 'screening',
    linkedin: 'https://linkedin.com/in/alejandrogomez',
    cv: 'https://example.com/cv/alejandro-gomez.pdf',
    years_of_experience: 3,
    applied_at: '2026-08-20T12:00:00Z',
    notes: [],
  },
];
